# permissions for end users to view flclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: flcluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kfl
    app.kubernetes.io/part-of: kfl
    app.kubernetes.io/managed-by: kustomize
  name: flcluster-viewer-role
rules:
- apiGroups:
  - kfl.aut.tech
  resources:
  - flclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kfl.aut.tech
  resources:
  - flclusters/status
  verbs:
  - get
