---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kfl.aut.tech
  resources:
  - flclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kfl.aut.tech
  resources:
  - flclusters/finalizers
  verbs:
  - update
- apiGroups:
  - kfl.aut.tech
  resources:
  - flclusters/status
  verbs:
  - get
  - patch
  - update
