apiVersion: kfl.aut.tech/v1alpha1
kind: FLCluster
metadata:
  name: fl-cluster-classic-1-1
  namespace: sample
spec:
  centralServer:
    replicas: 1
    resources:
      cpu: 1
      memory: 5Gi
  edgeClient:
    replicas: 1
    resources:
      cpu: 1
      memory: 5Gi